### ISSUE TITLE
Error: /Stage[main]/Kickstack::Nova::Api/Kickstack::Exportfact::Export[nova_metadata_ip]/Exportfact::Export[kickstack_nova_metadata_ip]/Augeas[fact_kickstack_nova_metadata_ip]: Could not evaluate: missing string argument 2 for set

### ISSUE THREAD

**Issue by darkyat** [cleura/kickstack#3]
Hello!

Unforatunately there is a Problem exporting the IP of Nova using "getvar("ipaddress_${nic_management}")" inside the exportfact.

I've also tried using:
      getvar("ipaddress_${::kickstack::nic_management}")
and many other methods to access it but it always seems to be null.

Error: /Stage[main]/Kickstack::Nova::Api/Kickstack::Exportfact::Export[nova_metadata_ip]/Exportfact::Export[kickstack_nova_metadata_ip]/Augeas[fact_kickstack_nova_metadata_ip]: Could not evaluate: missing string argument 2 for set.

Since it inherts from kickstack and includes kickstack::nova::config I don't get why it doesn't work. If I specify the IP hardcoded it works well and also the getvar works for other Modules.

Any Idea?

Thanks & Best Regards

**Comment by darkyat** [comment]
There is general problem all "ipaddress_" variables are not working for me.

**Comment by fghaas** [comment]
I can't reproduce that issue, but are you sure you actually have facter
installed on the machine(s) where you run the puppet agent?
